POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
content-type: application/json

{
  "date": "220-1-1",
  "specialist": "Nobody yet1",
  "type": "Hospital",
  "description": "Yearly control visit. Cholesterol levels skyrocketing.4",
  "healthCheckRating": 1
}

